### PR TITLE
Bug fix and improved logging.

### PR DESCRIPTION
**Pull request by snomos**

### CODE REVIEW

**Comment by roguePanda** [comment]
Would it be easier to remove `languageName:` and just use language codes everywhere? I think the name is only used for handle lookup since languages are registered with the spell server by code.

**Comment by snomos** [comment]
Sounds reasonable. Would there be a place to insert display language strings for languages lacking a language name in macosx?

**Comment by roguePanda** [comment]
Where are display language strings needed, though? It might be nice for logging, but I'm not sure where it's required if both Voikko and OS X use codes.

**Comment by snomos** [comment]
It would be nice to present to the user something different than 'olo', just like 'es' is not presented as 'es' but as 'Spanish' (or the equivalent in other languages). For languages like olo where macosx does not know what to name the code, we could provide something.

**Comment by roguePanda** [comment]
Using language codes instead of names for the handler dictionary in `VoikkoSpellChecker.m` fixes the crash, but the dictionary still shows up as `olo (MacVoikko)` in the preferences pane. I'm looking into how to register languages that OS X doesn't recognize, but I haven't found anything yet. Given that Klingon is an option in the "Language and Region" preferences, I'm sure there's a way to register additional languages.

**Comment by roguePanda** [comment]
After looking into it some more, I haven't found anything about adding additional languages. Many of the supported ones seem to be hard-coded into various configuration files and headers, so it might not be possible.

**Comment by snomos** [comment]
I don't know either whether it is possible, but I had hoped it would be. How is the display name generated?

**Comment by roguePanda** [comment]
I think most applications use `NSSpellChecker`, which provides a spelling panel and programmatic spell checking. I'm not sure how that's implemented but I assume it uses either `NSLocale` or some internal API that's not publicly accessible. I did find `International.framework` under `/System/Library/PrivateFrameworks`, and that has some language and country listings but not everything `NSLocale` knows about.

**Comment by snomos** [comment]
If there is no officially sanctioned way of providing language names outside of those covered by Apple, I think we should not bother more at the moment. I'll send a feature request or some such to Apple, and then we can see what to do later.

**Comment by roguePanda** [comment]
Sounds good. If you want, I can merge this then replace language names with language codes in `VoikkoSpellChecker.m`.

**Comment by snomos** [comment]
Yes, that sounds great.

**Pull request merged**
